# Generated by Django 5.2.8 on 2025-11-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance')], default='fantasy', max_length=50),
        ),
    ]
