# Generated by Django 5.2.8 on 2025-11-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_picture_url_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_copies',
        ),
    ]
