# Generated by Django 5.2.8 on 2025-11-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_book_picture_url_alter_book_genre'),
        ('librarians', '0001_initial'),
        ('members', '0003_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), (
                    'rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('date_borrowed', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='borrow_requests', to='book.book')),
                ('librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='processed_borrow_requests', to='librarians.librarian')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='borrow_requests', to='members.member')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
