# Generated by Django 5.2.8 on 2025-11-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='rejection_reason',
        ),
    ]
