# Generated by Django 5.2.8 on 2025-11-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_fields_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-date_joined']},
        ),
    ]
